# Generated by Django 4.1.4 on 2022-12-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgdb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_format', models.CharField(max_length=3)),
                ('text', models.TextField(max_length=500)),
                ('color', models.IntegerField()),
                ('background', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
