# Generated by Django 4.1.4 on 2022-12-30 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imgbun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdb',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
