# Generated by Django 4.1.4 on 2022-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgbun', '0004_imgdb_imagebun_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdb',
            name='imagebun_link',
            field=models.URLField(default='https//127.0.0.1:8000'),
        ),
    ]
